version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: melifresh
    ports:
      - 5432:5432

  redis:
    image: redis:3.2.5-alpine
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=master:redis
    ports:
      - "8081:8081"